apiVersion: apps/v1
kind: Deployment
metadata:
  name: platformservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: api
        image: joakimcarlssons/platformservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: platformservice
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: platformservice
spec:
  type: ClusterIP
  ports:
    - name: platformservice
      port: 5000
  selector:
    app: platformservice