# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
spec:
  accessModes:
    #- ReadWriteMany
    - ReadWriteOnce # The one allowed by Okteto
  resources:
    requests:
      storage: 200Mi